export const colors = {
  bg: "#080808",
  blue: "#1A6EFF",
  white: "#ffffff",
  muted: "rgba(255,255,255,0.3)",
  card: "rgba(255,255,255,0.05)",
  border: "0.5px solid rgba(255,255,255,0.1)",
};

export const sports = [
  "baseball",
  "basketball",
  "beach volleyball",
  "cross country",
  "fencing",
  "field hockey",
  "football",
  "golf",
  "gymnastics",
  "ice hockey",
  "lacrosse",
  "rowing",
  "rugby",
  "soccer",
  "softball",
  "swimming & diving",
  "tennis",
  "track & field",
  "volleyball",
  "water polo",
  "wrestling",
  "other",
];

export const schools = [
  "alabama a&m university",
  "arizona state university",
  "auburn university",
  "baylor university",
  "boston college",
  "brigham young university",
  "butler university",
  "clemson university",
  "colorado state university",
  "duke university",
  "florida a&m university",
  "florida state university",
  "fordham university",
  "georgetown university",
  "georgia tech",
  "gonzaga university",
  "harvard university",
  "howard university",
  "indiana university",
  "iowa state university",
  "kansas state university",
  "kentucky state university",
  "louisiana state university",
  "loyola university",
  "marquette university",
  "miami university",
  "michigan state university",
  "mississippi state university",
  "morehouse college",
  "north carolina a&t university",
  "north carolina state university",
  "northwestern university",
  "notre dame",
  "ohio state university",
  "oklahoma state university",
  "oregon state university",
  "penn state university",
  "purdue university",
  "rutgers university",
  "san diego state university",
  "seton hall university",
  "southern university",
  "st. johns university",
  "stanford university",
  "syracuse university",
  "temple university",
  "texas a&m university",
  "texas tech university",
  "tulane university",
  "unc chapel hill",
  "university of alabama",
  "university of arizona",
  "university of arkansas",
  "university of california berkeley",
  "university of california los angeles",
  "university of cincinnati",
  "university of colorado",
  "university of connecticut",
  "university of florida",
  "university of georgia",
  "university of houston",
  "university of illinois",
  "university of iowa",
  "university of kansas",
  "university of kentucky",
  "university of louisville",
  "university of maryland",
  "university of miami",
  "university of michigan",
  "university of minnesota",
  "university of mississippi",
  "university of missouri",
  "university of nebraska",
  "university of nevada las vegas",
  "university of new mexico",
  "university of north carolina",
  "university of notre dame",
  "university of oklahoma",
  "university of oregon",
  "university of pittsburgh",
  "university of south carolina",
  "university of southern california",
  "university of tennessee",
  "university of texas",
  "university of utah",
  "university of virginia",
  "university of washington",
  "university of wisconsin",
  "vanderbilt university",
  "villanova university",
  "virginia tech",
  "wake forest university",
  "washington state university",
  "west virginia university",
  "xavier university",
];

export type Airport = {
  code: string;
  city: string;
  name: string;
};

export const airports: Airport[] = [
  { code: "ATL", city: "atlanta", name: "hartsfield-jackson" },
  { code: "AUS", city: "austin", name: "austin-bergstrom" },
  { code: "BNA", city: "nashville", name: "nashville international" },
  { code: "BOS", city: "boston", name: "logan international" },
  { code: "BWI", city: "baltimore", name: "baltimore washington" },
  { code: "CLT", city: "charlotte", name: "charlotte douglas" },
  { code: "CMH", city: "columbus", name: "john glenn columbus" },
  { code: "CVG", city: "cincinnati", name: "cincinnati northern kentucky" },
  { code: "DCA", city: "washington", name: "ronald reagan washington" },
  { code: "DEN", city: "denver", name: "denver international" },
  { code: "DFW", city: "dallas", name: "dallas fort worth" },
  { code: "DTW", city: "detroit", name: "detroit metropolitan" },
  { code: "EWR", city: "newark", name: "newark liberty" },
  { code: "FLL", city: "fort lauderdale", name: "fort lauderdale hollywood" },
  { code: "HNL", city: "honolulu", name: "daniel k inouye" },
  { code: "IAD", city: "washington", name: "washington dulles" },
  { code: "IAH", city: "houston", name: "george bush intercontinental" },
  { code: "IND", city: "indianapolis", name: "indianapolis international" },
  { code: "JAX", city: "jacksonville", name: "jacksonville international" },
  { code: "JFK", city: "new york", name: "john f kennedy" },
  { code: "LAS", city: "las vegas", name: "harry reid international" },
  { code: "LAX", city: "los angeles", name: "los angeles international" },
  { code: "LGA", city: "new york", name: "laguardia" },
  { code: "MCI", city: "kansas city", name: "kansas city international" },
  { code: "MCO", city: "orlando", name: "orlando international" },
  { code: "MDW", city: "chicago", name: "midway international" },
  { code: "MEM", city: "memphis", name: "memphis international" },
  { code: "MIA", city: "miami", name: "miami international" },
  { code: "MKE", city: "milwaukee", name: "mitchell international" },
  { code: "MSP", city: "minneapolis", name: "minneapolis saint paul" },
  { code: "MSY", city: "new orleans", name: "louis armstrong new orleans" },
  { code: "OAK", city: "oakland", name: "oakland international" },
  { code: "ORD", city: "chicago", name: "o hare international" },
  { code: "ORF", city: "norfolk", name: "norfolk international" },
  { code: "PDX", city: "portland", name: "portland international" },
  { code: "PHL", city: "philadelphia", name: "philadelphia international" },
  { code: "PHX", city: "phoenix", name: "phoenix sky harbor" },
  { code: "PIT", city: "pittsburgh", name: "pittsburgh international" },
  { code: "RDU", city: "raleigh-durham", name: "raleigh-durham international" },
  { code: "RNO", city: "reno", name: "reno tahoe international" },
  { code: "SAN", city: "san diego", name: "san diego international" },
  { code: "SAT", city: "san antonio", name: "san antonio international" },
  { code: "SAV", city: "savannah", name: "savannah hilton head" },
  { code: "SEA", city: "seattle", name: "seattle-tacoma international" },
  { code: "SFO", city: "san francisco", name: "san francisco international" },
  { code: "SJC", city: "san jose", name: "norman y mineta san jose" },
  { code: "SLC", city: "salt lake city", name: "salt lake city international" },
  { code: "SMF", city: "sacramento", name: "sacramento international" },
  { code: "STL", city: "st louis", name: "st louis lambert" },
  { code: "TPA", city: "tampa", name: "tampa international" },
];
